package persistance;
// Generated 21 juil. 2018 16:49:00 by Hibernate Tools 3.4.0.CR1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int idclient;
     private String nom;
     private String prenom;
     private String adress;

    public Client() {
    }

	
    public Client(int idclient) {
        this.idclient = idclient;
    }
    public Client(int idclient, String nom, String prenom, String adress) {
       this.idclient = idclient;
       this.nom = nom;
       this.prenom = prenom;
       this.adress = adress;
    }
   
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }




}


